title_name = "Dead or Alive 5" # DOA5
title_id = "4B5607DA"  
hash = "B00E3FD1F2393598" # default.xex

[[patch]]
    name = "255-hit Combo Limit"
    desc = "Increases the combo limit from 30 to 255"
    author = "ryu_highabusa"
    is_enabled = true

    [[patch.be8]]
        address = 0x82406bd7
        value = 0xff